import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "./Components/Header/Header";
import Footer from "./Components/Header/Footer/Footer";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased flex flex-col min-h-screen`}
      >
        {/* header section  */}
        <header><Header /></header>

        {/* main section  */}
        <main className="flex-grow">{children}</main>

        {/* footer section  */}
        <footer><Footer /></footer>
      </body>
    </html>
  );
}
